ror/urls.py
from django.urls import path, include
from ror import views

app_name = 'ror'
urlpatterns = [
    path(
        'register/',
        views.RegisterAffiliations.as_view(),
        name='register_affiliations'),
    path(
        'about/',
        views.about,
        name='about'),
]

ror/templates/ror/about.html
{% extends 'base.html' %}
{% load i18n account socialaccount crispy_forms_tags %}

{% block head %}{{ form.media.css}}{% endblock head %}

{% block content %}
<div class='flex-grow-1 overflow-auto'>
  <div class='container content pt-5'>
    <header>{% trans "ROR and {{ site.name }}" %}</header>
  </div>
</div>
{% endblock content %}

ror/templates/ror/geoluminate_menu.html
{% load static i18n authentication %}

{% if user.is_authenticated %}
<li id='institutionDropdown' class="nav-item ms-auto dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="primary me-1 fas fa-university d-inline-block align-text-middle"></span>
    {% if user.ror_organization.exists %}
      {{user.ror_organization.first.name }}
    {% else %}
      {% trans "No Affiliations" %}
    {% endif %}
  </a>
  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
    {% if user.affiliation %}
      <li><a class="dropdown-item"  href="{% url 'user:profile' %}">{% trans "Profile" %}</a></li>
    {% else %}
      <li>
        <a href="{% url 'ror:register_affiliations' %}" class="dropdown-item">{% trans "Register an affiliation" %}</a>
      </li>
    {% endif %}
  </ul>
</li>
{% endif %}

ror/templates/ror/register_affiliations.html
{% extends 'base.html' %}
{% load i18n account socialaccount crispy_forms_tags %}

{% block head %}{{ form.media.css}}{% endblock head %}

{% block content %}
<div class='flex-grow-1 overflow-auto'>
  <div class='container content pt-5'>
    <header>{% trans "Select your affiliations" %}</header>
    {% blocktrans with site.name as site_name %}
    <p>{{ site_name }} integrates directly with the Research Organization Registry (ROR). </p>
    {% endblocktrans %}

    {% crispy form %}	
    <hr>
    <div id='affiliationList'>
      {% for org in organizations %}
        {% include "ror/components/affiliation.html" %}
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

{% block scripts %}
{{ form.media.js}}

<script>
    $('select').on('select2:select', function (e) {
      htmx.trigger('form', 'change')
      $('select').val(null).trigger('change')
    });

</script>

{% endblock scripts %}